services:
  app:
    build: .
    container_name: node-app-service
    ports:
      - "80:3000"  # Mapeia a porta 80 da VPS para a 3000 do Node
    env_file:
      - .env       # Carrega as vari√°veis de ambiente automaticamente
    restart: always # Faz o app ligar sozinho se a VPS reiniciar ou o app cair